name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{secrets.ACTION_SECRET}}
      PUBLISH_DIR: ./public
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: install_sass_compiler
        run: |
          npm i -g sass
      - name: compile_scss_file
        run: |
          sass scss:css
      - name: move_files
        run: |
          rsync -Rr ./*.html ./public
          rsync -Rr ./css ./public
      - name: Commit files
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.name githubaction
          git config --local user.email githubaction@fake.com
          git remote add origin https://$MY_SECRET@github.com/Mashar-io/official-website.git
          echo $MY_SECRET and $GITHUB_REPOSITORY
          git checkout -b gh-pages
          git add .
          git commit "gh-pages"
          git status
          git push origin gh-pages
          echo ðŸ¤˜ deploy gh-pages complete.
